import Card from "@material-tailwind/react/Card";
import CardBody from "@material-tailwind/react/CardBody";
import Input from "@material-tailwind/react/Input";
import Button from "@material-tailwind/react/Button";
import Dropdown from "@material-tailwind/react/Dropdown";
import DropdownItem from "@material-tailwind/react/DropdownItem";
import DropdownLink from "@material-tailwind/react/DropdownLink";
import Small from "@material-tailwind/react/Small";
import H6 from "@material-tailwind/react/Heading6";

export default function OutLetEdit({ showOutletDetail, setShowOutletDetail }) {
  return (
    <>
      {showOutletDetail && (
        <button
          className="flex text-4xl text-black items-center cursor-pointer fixed right-10 top-6 z-50"
          onClick={() => setShowOutletDetail(!showOutletDetail)}
        >
          x
        </button>

      )}
      <div className={`top-0 bottom-0 right-0 w-[35vw] overflow-auto bg-white p-10 pl-20 text-white fixed h-full z-40 ease-in-out duration-300 ${showOutletDetail ? "translate-x-0 " : "translate-x-full"}`}>
        <form>
        <H6 color="gray">
          Equipment,
              <br />
              Information
            </H6>
          <div className="flex flex-wrap mt-10 items-end">
            <div className="w-full lg:w-4/12 pr-4 mb-10 font-light">
              <Small color="gray">Equipment ID</Small>
              <Input
                type="text"
                size="regular"
                outline={true}
                placeholder="Generated by system"
              />
            </div>
            <div className="w-full lg:w-4/12 pl-4 mb-10 font-light">
              <Small color="gray">Type</Small>
              <Dropdown
                placement="bottom-start"
                buttonText="Type"
                buttonType="outline"
                size="regular"
                block={true}
                ripple="dark"
              >
                <DropdownItem ripple="light">Action</DropdownItem>
                <DropdownLink
                  href="#"
                  color={"red"}
                  ripple="light"
                  onClick={(e) => e.preventDefault()}
                >
                  Another Action
                </DropdownLink>
                <DropdownItem color="lightBlue" ripple="light">
                  Something else
                </DropdownItem>
              </Dropdown>
            </div>

            <div className="w-full lg:w-4/12 pl-4 mb-10 font-light">
              <Small color="gray">Equipment Name</Small>
              <Input type="text" size="regular" outline={true} />
            </div>
            <div className="w-full lg:w-4/12 pr-4 mb-10 font-light">
              <Small color="gray">Equipment Serial No.</Small>
              <Input type="text" size="regular" outline={true} />
            </div>
            <div className="w-full lg:w-4/12 pl-4 mb-10 font-light">
              <Small color="gray">Equipment Manufacture</Small>
              <Input type="text" size="regular" outline={true} />
            </div>
            <div className="w-full lg:w-4/12 pl-4 mb-10 font-light">
              <Small color="gray">Equipment Model</Small>
              <Input type="text" size="regular" outline={true} />
            </div>
          </div>
          <h6 className="text-purple-500 text-sm mt-3 mb-6 font-light uppercase">
            <b>Energy</b>
            <br /> Information
          </h6>
          <div className="flex flex-wrap mt-10">
            <div className="w-full lg:w-4/12 pr-4 mb-10 font-light">
              <Small color="gray">Baseline</Small>
              <Input type="text" size="regular" outline={true} />
            </div>
            <div className="w-full lg:w-4/12 pl-4 mb-10 font-light">
              <Small color="gray">Usage - Low</Small>
              <Input type="text" size="regular" outline={true} />
            </div>
            <div className="w-full lg:w-4/12 pl-4 mb-10 font-light">
              <Small color="gray">Usage - High</Small>
              <Input type="text" size="regular" outline={true} />
            </div>
          </div>

          <div className="flex flex-row justify-between">
            <h6 className="text-purple-500 text-sm mt-3 mb-6 font-light uppercase">
              <b>Device</b>
            </h6>
            <h5 className="text-gray-500 text-sm mt-3 mb-6 font-light uppercase">
              <b>(0)</b>
            </h5>
          </div>
          <div className="flex flex-wrap mt-10 items-stretch">
            <div className="w-full lg:w-8/12 pr-4 mb-10 font-light">
              <Dropdown
                placement="bottom-start"
                buttonText="Type"
                buttonType="outline"
                size="sm"
                block={true}
                ripple="dark"
              >
                <DropdownItem ripple="light">Action</DropdownItem>
                <DropdownLink
                  href="#"
                  color={"red"}
                  ripple="light"
                  onClick={(e) => e.preventDefault()}
                >
                  Another Action
                </DropdownLink>
                <DropdownItem color="lightBlue" ripple="light">
                  Something else
                </DropdownItem>
              </Dropdown>
            </div>
            <div className="w-full lg:w-4/12 pl-4 mb-10 font-light">
              <Button
                buttonType="filled"
                size="regular"
                rounded={false}
                block={false}
                iconOnly={false}
                ripple="light"
              >
                <span>Retrieve from Emily</span>
              </Button>
            </div>
          </div>
          <div className="flex flex-wrap mt-10">
            <div className="w-full lg:w-6/12 pr-4 mb-10 font-light">
              <Button
                buttonType="outline"
                size="regular"
                rounded={false}
                block={true}
                iconOnly={false}
                ripple="dark"
              >
                Reset
              </Button>
            </div>
            <div className="w-full lg:w-6/12 pl-4 mb-10 font-light">
              <Button
                buttonType="filled"
                size="regular"
                rounded={false}
                block={true}
                iconOnly={false}
                ripple="light"
              >
                Save
              </Button>
            </div>
          </div>
        </form>
      </div></>
  );
}
